In [1]:
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from db_initialize import *

engine = create_engine('sqlite://///Users/Johnson/Documents/nit/thesis/forum_crawler/database_test.db')
Session = sessionmaker(bind=engine)
Base.metadata.bind = engine
session = Session()

In [2]:
users = session.query(User).order_by(User.name).all()
len(users)
for user in users:
    print(user)

User <0311> is from forum <healing well>, has 0 threads, 1 posts.
User <1218davinci> is from forum <healing well>, has 0 threads, 1 posts.
User <60Michael> is from forum <healing well>, has 0 threads, 2 posts.
User <614-2101-765-611> is from forum <healing well>, has 0 threads, 1 posts.
User <81GyGuy> is from forum <healing well>, has 3 threads, 2 posts.
User <ASAdvocate> is from forum <healing well>, has 0 threads, 7 posts.
User <Aimzee> is from forum <healing well>, has 0 threads, 2 posts.
User <Almost a 10> is from forum <healing well>, has 0 threads, 6 posts.
User <AnotherDisplayName> is from forum <healing well>, has 0 threads, 1 posts.
User <Artist Mark> is from forum <healing well>, has 2 threads, 4 posts.
User <BOOGEE> is from forum <healing well>, has 0 threads, 2 posts.
User <Berdoo/Arkansas> is from forum <healing well>, has 1 threads, 1 posts.
User <Big Mac> is from forum <healing well>, has 0 threads, 1 posts.
User <BillyBob@388> is from forum <healing well>, has 0 threads

In [2]:

author = session.query(User).filter_by(name="LowRoad", forum="prostatakrebs").first()
len(author.threads)

48

In [2]:
from sqlalchemy import inspect
inspector = inspect(engine)

inspector.get_table_names()
for column in inspector.get_columns('threads'):
   print("Column: %s" % column['name'])

Column: id
Column: user_id
Column: url
Column: body
Column: timestamp
Column: title
Column: forum
Column: subforum
Column: subforum_url


In [6]:
posts = session.query(Post).filter_by(subforum='Angehörigenforum').all()
len(posts)

307

In [7]:
threads = session.query(Thread).filter_by(subforum='Prostatakrebs und Psyche').all()
len(threads)

68

In [2]:
user3 = User(name="liangcheng", subforum="c")
session.add(user3)
session.commit()

In [11]:
user = session.query(User).filter_by(name="liangcheng").first()

In [12]:
user

In [10]:
session.delete(user)
session.commit()

In [3]:
num = session.query(Thread).count()


In [4]:
num

28850

In [3]:

thread = session.query(Thread).all()
print(len(thread))
#print(len(thread.posts))
for x in range(1,20):
    print(thread[x])

46

Title: Viagra, Cialis u.s.w. Einfluss auf Tumorprogression? 
User: Conobar 
Time: 2011-01-14 16:59:00 
Posts: 22
URL: http://forum.prostatakrebs-bps.de/showthread.php?6220-Viagra-Cialis-u-s-w-Einfluss-auf-Tumorprogression 

					Hallo, 

mich würde interessieren, ob Studien existieren über den Einfluss von Viagra, Cialis,Levitra u.ä. auf das Tumorverhalten bei Patienten , welche als Therapie die intermittierende Hormontherpie gewählt haben.

MfG
				 


Title: Zytiga: häufige Nebenwirkungen Herzversagen, Sepsis? 
User: wolfgang61 
Time: 2015-06-05 19:40:00 
Posts: 9
URL: http://forum.prostatakrebs-bps.de/showthread.php?8981-Zytiga-h%C3%A4ufige-Nebenwirkungen-Herzversagen-Sepsis 

					Hallo,

seit zwei Monaten bekomme ich Zytiga. Seit kurzer Zeit macht das Herz Extraschläge. Laut Internist liegt es noch im Toleranzbereich. Aber im Beipackzettel findet man auch unter häufigen Nebenwirkungen (1 von 10) Herzversagen. 

Wer hat Erfahrung mit Zytiga oder entsprechende Informationsquelle

In [7]:
for x in range(1,20):
    thread[x].body

In [2]:
import re
line = " \nI am having a very nice day."
count = len(re.findall(r'\w+', line))
print (count)
print (line)

7
 
I am having a very nice day.


In [3]:
def word_count(doc):
    count = len(re.findall(r'\w+', doc))
    return count

In [35]:
thread = session.query(Thread).get(0)

In [37]:
type(thread)

NoneType

In [10]:
thread = session.query(Thread).filter_by(url="http://www.healingwell.com/community/default.aspx?f=35&m=3674693").first()
thread.posts[1].forum
thread.posts

[
 User: Newton451 
 Time: 2016-07-29 07:55:00 
 Thread: Do you have a favorite saying? 
 Order: None 
 URL: http://www.healingwell.com/community/default.aspx?f=35&m=3674693 
 Everywhere ya go.....there ya are!
 
 I know you think you understand what you think I said, but what you heard isn't really what I meant. ,
 
 User: alephnull 
 Time: 2016-07-29 08:16:00 
 Thread: Do you have a favorite saying? 
 Order: None 
 URL: http://www.healingwell.com/community/default.aspx?f=35&m=3674693 
 It ain't over till it's over ,
 
 User: 81GyGuy 
 Time: 2016-07-29 08:22:00 
 Thread: Do you have a favorite saying? 
 Order: None 
 URL: http://www.healingwell.com/community/default.aspx?f=35&m=3674693 
 "Live above cancer."
 
 From a post entered here on this very forum not long ago. (By MsWorryWart, if memory serves).
 
 Well, maybe it's more of a motto than a saying, but it sure is relevant. ,
 
 User: Herophilus 
 Time: 2016-07-29 08:34:00 
 Thread: Do you have a favorite saying? 
 Order: None 
 U

In [46]:
import csv
with open('posts.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile)
    for x in range(0,10):
        thread = session.query(Thread).get(x+1)
        spamwriter.writerow([thread.title, thread.timestamp, thread.body])

In [35]:
from bs4 import BeautifulSoup
def body_parser(body):
    if body.find('<hr class="PostHR">') != -1:
        body = body[:body.find('<hr class="PostHR">')]
    body = body.replace("<br>","NEWLINE")
    soup = BeautifulSoup(body, 'html.parser')
    text = soup.get_text()
    return text.replace("NEWLINE", "\n")

In [36]:
s = "<div class=\"PostMessageBody\">Hi all<br><br>I have been waking up with some discomfort on my right side, i believe it's my lymph node... when I feel carefully I can fill it inflamed.... my CT showed no lymph node involvement, but I'm having some considerable discomfort on the same side my cancer was found with the biopsy (R apex)... feels like a small swollen small rock.<br><br>Going for my Cysto tomorrow, I think I'm going to ask my urologist about<strong></strong> it ... has anyone else had similar symptoms?<br><br>Thanks<br>Zzarth<hr class=\"PostHR\">6/10/16 - first ever PSA results in a 15.1<br>7/25/16 - Biopsy results in G6, 4mm 30% of tissue<br>8/1/16 - started antibiotics to rule out prostatitis  <br>8/5/16 - Hopkins Results in Upgrade to G3+4=7 (Grade group 2), 70%, 10% G4<br>8/5/16 - CT of Prostate shows no lymph node involvement<br>8/10/16 - Laid off from new job when boss learns of my cancer<br>8/17/16 - PSA tested @ 18.0</div>"
ss = body_parser(s)
print(ss)

Hi all

I have been waking up with some discomfort on my right side, i believe it's my lymph node... when I feel carefully I can fill it inflamed.... my CT showed no lymph node involvement, but I'm having some considerable discomfort on the same side my cancer was found with the biopsy (R apex)... feels like a small swollen small rock.

Going for my Cysto tomorrow, I think I'm going to ask my urologist about it ... has anyone else had similar symptoms?

Thanks
Zzarth


In [33]:
body = s
body = body.replace("<br>","NEWLINE")
body
soup = BeautifulSoup(body,"html.parser")

In [34]:
soup

<div class="PostMessageBody">Hi allNEWLINENEWLINEI have been waking up with some discomfort on my right side, i believe it's my lymph node... when I feel carefully I can fill it inflamed.... my CT showed no lymph node involvement, but I'm having some considerable discomfort on the same side my cancer was found with the biopsy (R apex)... feels like a small swollen small rock.NEWLINENEWLINEGoing for my Cysto tomorrow, I think I'm going to ask my urologist about<strong></strong> it ... has anyone else had similar symptoms?NEWLINENEWLINEThanksNEWLINEZzarth<hr class="PostHR">6/10/16 - first ever PSA results in a 15.1NEWLINE7/25/16 - Biopsy results in G6, 4mm 30% of tissueNEWLINE8/1/16 - started antibiotics to rule out prostatitis  NEWLINE8/5/16 - Hopkins Results in Upgrade to G3+4=7 (Grade group 2), 70%, 10% G4NEWLINE8/5/16 - CT of Prostate shows no lymph node involvementNEWLINE8/10/16 - Laid off from new job when boss learns of my cancerNEWLINE8/17/16 - PSA tested @ 18.0</hr></div>

In [12]:
import numpy as np
y = [1,2,3,4,6]
y_np = np.array(y)

In [8]:
np.histogram(y_np, np.arange(1, len(y_np)+1))

(array([1, 1, 2]), array([1, 2, 3, 4]))

In [13]:
np.bincount(y_np)

array([0, 1, 1, 1, 1, 0, 1])

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [17]:
import numpy as np
thread = session.query(Thread).get(8)
post_timestamps = np.array([post.timestamp for post in thread.posts], dtype='datetime64')

In [18]:
post_timestamps

array(['2016-08-10T01:02:00', '2016-08-10T01:09:00', '2016-08-10T02:49:00',
       '2016-08-10T03:10:00', '2016-08-10T03:44:00', '2016-08-10T05:41:00',
       '2016-08-10T05:54:00', '2016-08-10T07:01:00', '2016-08-10T08:16:00',
       '2016-08-10T08:20:00', '2016-08-10T09:07:00', '2016-08-10T09:39:00',
       '2016-08-10T10:06:00', '2016-08-10T10:08:00', '2016-08-10T10:30:00',
       '2016-08-10T10:34:00', '2016-08-10T11:14:00', '2016-08-10T11:47:00',
       '2016-08-10T00:13:00', '2016-08-10T00:14:00', '2016-08-10T17:02:00',
       '2016-08-10T17:41:00', '2016-08-10T19:07:00', '2016-08-10T20:45:00',
       '2016-08-11T12:06:00', '2016-08-11T12:36:00', '2016-08-11T08:24:00',
       '2016-08-11T21:07:00', '2016-08-12T21:03:00', '2016-08-13T20:57:00',
       '2016-08-14T02:05:00', '2016-08-14T08:59:00'], dtype='datetime64[s]')

In [10]:
min(post_timestamps)

numpy.datetime64('2016-08-29T00:55:00')

In [19]:
thread.posts

[
 User: island time 
 Time: 2016-08-10 01:02:00 
 Thread: Against all odds 
 Order: None 
 URL: http://www.healingwell.com/community/default.aspx?f=35&m=3680792 
 That's what I'm talking about !!
 
 Smile , 
 User: Maryanddan 
 Time: 2016-08-10 01:09:00 
 Thread: Against all odds 
 Order: None 
 URL: http://www.healingwell.com/community/default.aspx?f=35&m=3680792 
 Congratulations! What wonderful news! It provides much needed encouragement as Dan's PSA continues to rise throughout taxotere treatments. I showed him your history of treatments just today so he'd realize there are still many options. Thanks for sharing. Mary , 
 User: CaliJR 
 Time: 2016-08-10 02:49:00 
 Thread: Against all odds 
 Order: None 
 URL: http://www.healingwell.com/community/default.aspx?f=35&m=3680792 
 Wow Beth, that is a great update!  I wish you and Gary continued success with the new treatments.  Take care! -JR , 
 User: Tall Allen 
 Time: 2016-08-10 03:10:00 
 Thread: Against all odds 
 Order: None 
 URL

In [12]:
x = 4
if 3 <= x <= 5:
    print(x)

4


In [36]:
if 3<=x and x<=5:
    print(x)
thread.timestamp

4


'2016-08-10 12:47:00'

In [33]:
from datetime import datetime

date_object = datetime.strptime('Jun 1 2005  1:33PM', '%b %d %Y %I:%M%p')
def get_time_span(thread):
    #post_timestamps = np.array([post.timestamp for post in thread.posts], dtype='datetime64')
    # assume the last post in thread.posts is the last reply
    thread_time = datetime.strptime(thread.timestamp, '%Y-%m-%d %H:%M:%S')
    last_reply_time = datetime.strptime(thread.posts[-1].timestamp, '%Y-%m-%d %H:%M:%S')
    time_delta = last_reply_time - thread_time
    print(time_delta)
    #calculate the time span in hours
    time_span = 24*int(time_delta.days) + time_delta.seconds//3600
    return time_span

In [34]:
get_time_span(thread)

3 days, 20:12:00


92

In [26]:
import numpy as np
x = np.empty([1,2],dtype="int32")

In [27]:
print(x.shape)
x[1] = 2

(1, 2)


IndexError: index 1 is out of bounds for axis 0 with size 1

In [15]:
5%2

1

In [28]:
a = [1,2,3]
np.save('test_save',a)

In [29]:
b = np.load('test_save.npy')

In [30]:
b

array([1, 2, 3])